<!doctype html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Login</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    </head>
    <body>
        <div class="row" style="width: 100%;height: 100%;position: fixed;top:0;left:0;margin:0;padding:0;display: flex;align-items: center;justify-content: center;overflow: auto">
            <div class="col-12 col-lg-3">
                <div class="card text-secondary">
                    <div class="card-header"><h2 class="text-center">Авторизация</h2></div>
                    <div class="card-body">
                        <div class="row mb-3">
                            <label for="login" class="form-label col-4">Пользователь</label>
                            <div class="col-8">
                                <input type="login" class="form-control" id="login">
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label for="password" class="col-4 form-label">Пароль</label>
                            <div class="col-8">
                                <input type="password" class="form-control" id="password">
                            </div>
                        </div>
                        <button type="button" class="btn btn-secondary" id="submit">Вход</button>
                    </div>
                </div>
            </div>
        </div>
        <script>
            document.addEventListener("DOMContentLoaded", function(event) {
                $('#submit').on('click',function(){
                    var loginInput = $('#login'),
                        passwordInput = $('#password');
                    $.post(
                        '/admin/login',
                        {
                            login:$(loginInput).val(),
                            password:$(passwordInput).val()
                        },
                        function(response){
                            if(response.success) {
                                console.log(response.link);
                                window.location.href = response.link;
                            }
                            else{
                                $(loginInput).addClass('is-invalid');
                                $(passwordInput).addClass('is-invalid');
                            }
                        },
                        'json'
                    );
                });
            });
        </script>
        <script type="text/javascript" src="/js/base/jquery-3.6.0.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    </body>
</html>