<!DOCTYPE html>
<html lang="<?=$data->lang;?>">
<head>
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><?=$data->title;?></title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta http-equiv="content-type" content="text/html; charset=utf-8">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <!-- Соц.сети -->
    <meta property="og:locale" content="ru_RU"/>
    <meta property="og:type" content="article"/>
    <meta property="og:title" content="Главная | SCERN"/>
    <meta property="og:description" content=""/>
    <meta property="og:image" content=""/>
    <meta property="og:url" content=""/>
    <meta property="og:site_name" content="SCERN"/>
    <link rel="icon" href="/favicon.ico?v=2">
</head>
<body style="background: url('/images/bg.png') fixed;">
<div class="container p-1" style="background-color: rgba(255, 255, 255, 0.6);">
    <div class="row no-gutters">
        <div class="col-xs-12 col-sm-12 col-md-9 col-lg-10 col-xl-10">
            <h1 class="display-3">
                <a href="/" title="SCERN" class="text-primary" style="text-decoration:none;">SCERN</a>
            </h1>
            <h4 class="text-success"><i>Progress. Making great. No harm</i></h4>
        </div>
    </div>
    <div class="row no-gutters">
        <div class="col-xs-12 col-md-12 col-lg-12">
        </div>
    </div>
    <div class="row no-gutters">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-9 order-lg-6 col-xl-9">
            <form action="" method="POST" role="form" class="m-1">
                <div class="row no-gutters">
                    <div class="col-sm-11 p-1">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <div class="input-group-text border-secondary text-dark">
                                    <i class="fa fa-search"></i>
                                </div>
                            </div>
                            <input class="form-control border-secondary text-dark" type="text" id="search" name="search" autocomplete="off" placeholder="Поиск" onkeydown="return event.key != 'Enter';" />
                        </div>
                    </div>
                    <div class="col-sm-1 p-1">
                        <input class="btn btn-light border-secondary" type="button" value="Поиск" />
                    </div>
                </div>
            </form>					<div class="m-1 p-2 rounded-top" style="background-color: rgba(255, 255, 255, 0.9);">
                <div class="clearfix">
                    <?=$data->content;?>

                    <h1 class="text-center"><a href="https://scern.ru"></a></h1>

                    <h2 style="text-align:center"><span style="color:#27ae60">Добро пожаловать</span></h2>

                    <p><img alt="" class="img-thumbnail" src="/images/medium_4104d8c8a91887c609a5.jpg" style="float:left; margin:5px; width:260px" />Я - Дмитрий Диденко.&nbsp;</p>

                    <p>Fullstack web-разработчик (PHP+JS+HTML), DevOps, электронщик.</p>

                    <p>Живу в Воронеже.&nbsp;</p>

                    <p>Работаю web-разработчиком и системным администратором. Занимаюсь настройкой/поддержкой WEB-серверов и разработкой&nbsp;сайтов (в том числе интернет-магазинов).</p>

                    <p>Интересуюсь технологиями искусственного интеллекта, систем автоматизации и умного дома. Люблю систематизировать, структурировать, обобщать информацию, составляя справочники и каталоги. Путешествовать и фотографировать. Приверженец здорового образа жизни,&nbsp;без фанатизма.</p>

                    <p>Работал специалистом технической поддержки (в том числе в колл-центре), контент-менеджером,&nbsp;помощником системного администратора интернет-провайдера, инженером аутсорсинговой компании, администратором WEB-серверов и серверов баз данных, сетевым инженером/администратором.</p>

                    <p>Занимался графическим дизайном, переносом изображений на носитель/подложку (термоперенос), сбором мебели, вертикальных жалюзи. Монтажем локальных сетей, систем видеонаблюдения. Программированием контроллеров автоматизации (охрана, противопожарные).&nbsp;WEB-разработкой на PHP и JS, блочной вёрсткой. Созданием конфигурации 1С. Сборкой, несложным ремонтом и обслуживанием вычислительной и печатной техники. Настройкой IP и аналоговой телефонии.</p>

                    <p>Имею техническое образование:</p>

                    <p>высшее: Химик-технолог (производство минеральных удобрений);</p>

                    <p>среднее: Электромонтажник (промышленных установок и гражданских сооружений).</p>

                    <p>&nbsp;</p>

                    <p>Примерно&nbsp;15 лет работы в IT.</p>

                    <p>Прошел&nbsp;курсы HTML вёрстки и дизайна, сертификацию ZyXEL (ZCSE, ZCSA).&nbsp;</p>

                    <p>Участвовал в конференциях, meetup-ах, и даже хакатоне</p>

                    <p>&nbsp;</p>

                    <p>Разработка <a href="#">платформы &quot;Лира&quot;</a>, на основе которой возможно&nbsp;создавать сайты, каталоги, порталы и стала причиной появления этого сайта.</p>

                    <p>Задуманный как персональная страница, или личный блог, этот сайт стал&nbsp;площадкой для публикации материалов как о самой платформе, так и собственных статей об интересных мне направлениях.</p>

                    <p>Надеюсь, размещенные на этом сайте материалы могут оказаться полезными вам!</p>

                    <div class="clearfix">
                    </div>
                </div>						</div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-3 order-lg-1 col-xl-3">
            <ul id="menu">
                <li>
                    <a href="/" target="" title="Главная">Главная</a>

                </li>
                <li><!--
			<a href="/interested_in" target="" title="Мне интересно">Мне интересно</a>

		</li>
										<li>
			<a href="/documentation" target="" title="Документация">Документация</a>

		</li> -->

        </div>
    </div>
    <div class="row no-gutters" style="height:100px;">
        <div class="col-xs-12">

        </div>
    </div>
    <div class="footer bg-dark text-light">
        <div class="row no-gutters">
            <div class="col-md-3">
                <div class="m-2">
                    <div itemscope itemtype="http://schema.org/Person">
                        <span itemprop="name">Дмитрий</span>&nbsp;
                        <span itemprop="additionalName">Евгениевич</span>&nbsp;
                        <span itemprop="familyName">Диденко</span><br/>
                        <span itemprop="jobTitle" class="text-warning">Системный администратор, WEB-разработчик</span><br/>
                        <span itemprop="telephone">+7(909) 409-21-62</span>,&nbsp;
                        <span itemprop="email">scern@mail.ru</span><br/>
                    </div>
                </div>
            </div>
            <div class="col-md-3 d-none d-lg-block">
            </div>
            <div class="col-md-3 d-none d-lg-block">
                <div class="p-3">
                    <p><a class="text-light" href="https://vk.com/scern" target="_blank"><img src="/images/vk.png" width="30"/> <strong>ВКонтакте</strong></a></p>			</div>
            </div>
            <div class="col-md-3 d-none d-lg-block">
                <div class="p-1">
                    <p class="text-light text-center mb-0"><small>SCERN © 2012-2022</small></p>
                    <p class="text-warning text-center mb-0"><small>Разработка <a class="text-light" href="https://scern.ru">Scern</a></small></p>
                    <p class="text-warning text-center mb-0"><small><a class="text-warning" href="#">Платформа "Лира" v6.5</a></small></p>
                </div>
                <div class="p1 text-center">
                    <a href="#" data-lng="ru" class="link lng-select">RU</a>
                    <a href="#" data-lng="en" class="link lng-select">EN</a>
                    <a href="#" data-lng="de" class="link lng-select">DE</a>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="/js/base/jquery-3.6.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $('#menu').slicknav();
        // Смена языка
        $('.lng-select').on('click',function(e){
            e.preventDefault();
            window.location = ((window.location + '').replace(/.ru\/[a-z]{2}/, '.ru/' + $(this).attr('data-lng')));
        });

    });
</script>

<!-- LEFT Vertical Slicknav menu -->
<link rel="stylesheet" href="/styles/style.css">
<script src="/js/plugins/jquery.slicknav.js"></script>
<script src="/js/plugins/modernizr.min.js"></script>


<!-- FOOTER Vertical menu -->
<link rel="stylesheet" href="/styles/footer_menu.css">
</body>
</html>